36 addbackbutton
GSG-FC03/Cookit pull request #38
Opened 2021-08-12 16:30 UTC by FatmaHossam5

adding back button to allow user to move to main page to choose meals from desired country 
adding reload button to refresh a cuisine page and return to origin

2021-08-12 20:02 UTC, Rola-H approved these changes, later dismissed

2021-08-12 21:03 UTC, lina-jamal requested changes
add width =100% to the tag image 
![Screenshot from 2021-08-12 23-59-03](https://user-images.githubusercontent.com/52348749/129269499-c6808c4a-c4cb-47ea-9338-14934d2b4329.png)

2021-08-12 21:03 UTC, lina-jamal commented on cousins/cuisine.css
> +.back-Btn{
the style is not perfect in iPhone x 
show as 
![Screenshot from 2021-08-12 23-58-32](https://user-images.githubusercontent.com/52348749/129269310-798c7583-53ee-475c-96a9-efcc365b1f36.png)

2021-08-13 11:30 UTC, MahmoudJD95 approved these changes

2021-08-13 13:01 UTC, lina-jamal approved these changes

2021-08-13 13:01 UTC, merged